# Generated by Django 3.2.13 on 2022-06-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_instagram',
            field=models.URLField(blank=True),
        ),
    ]
